let token='',run,offer,config,busy=false;const expected='0x7034af41397893321c4458abb3b98f6c67065fab',chain='0x14a34';const $=id=>document.getElementById(id);
function show(v){$('output').textContent=JSON.stringify(v,null,2);}
async function api(path,body){const r=await fetch('/v1/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const v=await r.json();if(!r.ok)throw Error(v.error);return v;}
async function wallet(){if(!window.ethereum)throw Error('Open this console in a browser with your wallet extension.');const accounts=await ethereum.request({method:'eth_requestAccounts'});if(accounts[0]?.toLowerCase()!==expected)throw Error('Wrong wallet. Select '+expected);if(await ethereum.request({method:'eth_chainId'})!==chain)throw Error('Switch your wallet to Base Sepolia (84532) and retry.');return accounts[0];}
async function sign(message){const account=await wallet();const hex='0x'+Array.from(new TextEncoder().encode(message),b=>b.toString(16).padStart(2,'0')).join('');return ethereum.request({method:'personal_sign',params:[hex,account]});}
async function send(tx){await wallet();const request={from:expected,data:tx.data,value:'0x0',...(tx.to?{to:tx.to}:{})};show(tx);return ethereum.request({method:'eth_sendTransaction',params:[request]});}
async function confirm(path,transactionHash){for(let n=0;n<40;n++){try{return await api(path,{transactionHash});}catch(e){if(!['DEPENDENCY_UNAVAILABLE','INSUFFICIENT_CONFIRMATIONS'].includes(e.message))throw e;await new Promise(r=>setTimeout(r,3000));}}throw Error('Confirmation pending. Preserve transaction hash: '+transactionHash);}
async function refresh(){config=await api('config');const offers=await api('offers');offer=offers.find(o=>o.status!=='REPAID')??offers.at(-1);show({config,offers,receipts:await api('receipts'),graph:await api('graph'),wallet:await api('wallet')});for(const id of ['analyze','refresh'])$(id).disabled=false;$('deploy').disabled=!!config.deployment;$('offer').disabled=!run||!!offer;$('approve').disabled=!offer||offer.status!=='PROPOSED'||!config.deployment;$('allowance').disabled=!offer||!['APPROVED','DRAWN'].includes(offer.status);$('register').disabled=!offer||offer.status!=='APPROVED';$('draw').disabled=!offer||offer.status!=='REGISTERED';$('repay').disabled=!offer||offer.status!=='DRAWN';}
const actions={connect:async()=>{await wallet();const c=await api('auth/challenge',{});token=(await api('auth/verify',{id:c.id,signature:await sign(c.message),chainId:84532})).token;await refresh();},analyze:async()=>{run=await api('runs',{question:'Can I still place this inventory order?',purchaseId:'restock-1',horizonDays:35});await refresh();show(run);},deploy:async()=>{const tx=await api('deployment/prepare',{});const hash=await send(tx);$('status').textContent='Deployment submitted: '+hash;await confirm('deployment/verify',hash);await refresh();},offer:async()=>{offer=await api('offers',{runId:run.id});await refresh();},approve:async()=>{const a=await api('offers/'+offer.id+'/approval',{});show(a);await api('offers/'+offer.id+'/approve',{signature:await sign(a.message),chainId:84532});await refresh();},refresh};
for(const action of ['allowance','register','draw','repay'])actions[action]=async()=>{const amount=offer?(BigInt(offer.principal)+BigInt(offer.fee)-BigInt(offer.repaid)).toString():undefined;const tx=await api('offers/'+offer.id+'/prepare',{action,...(action==='repay'?{amount}:{})});const hash=await send(tx);$('status').textContent='Submitted '+hash;if(action!=='allowance')await confirm('offers/'+offer.id+'/reconcile',hash);else $('status').textContent='Allowance submitted. Wait for wallet confirmation before the next action. '+hash;await refresh();};
for(const [id,action] of Object.entries(actions))$(id).onclick=async()=>{if(busy)return;busy=true;try{await action();if(id!=='allowance')$('status').textContent='Completed. Inspect the evidence below.';}catch(e){$('status').textContent=e.message;}finally{busy=false;}};
window.ethereum?.on?.('accountsChanged',()=>{token='';location.reload();});window.ethereum?.on?.('chainChanged',()=>{token='';location.reload();});
