import {randomBytes} from 'node:crypto';
import {verifyMessage} from 'viem';
import type {Hex,Address} from 'viem';
import {Store} from './store.ts';
import {fixture,ensure,hash,OWNER,CHAIN} from './domain.ts';
import type {Graph,Run} from './domain.ts';
import {analyze,validateAgentIntent} from './skills.ts';
import {issueOffer,authorizeOffer,approvalMessage} from './policy.ts';
import type {Offer} from './policy.ts';
import {deployment,verifyDeployment,verifyReceipt,transaction} from './chain.ts';

type Challenge={message:string;expiresAt:number;used:boolean};
export interface AccountRow{address:string;business:string;graphId:string;graphVersion:number;graphAsOf:number;createdAt:number;lastSeenAt:number;runs:number;offers:number;receipts:number;}
export class Service {
 store:Store; owner:string; clock:()=>number;
 constructor(store:Store,owner=OWNER,clock=Date.now){this.store=store;this.owner=owner.toLowerCase();this.clock=clock;if(!store.get('graph','adas-pharmacy')){store.insert('graph','adas-pharmacy',fixture(clock()));store.insert('private','commitment-salt',randomBytes(32).toString('hex'));store.audit({event:'DEMO_GRAPH_SEEDED',at:clock()});}}
 graph(){return this.store.get<Graph>('graph','adas-pharmacy')!;}
 challenge(){const id=randomBytes(24).toString('hex'),expiresAt=this.clock()+300000;const message=`Kora local development sign-in\nOrigin: http://localhost:4001\nWallet: ${this.owner}\nChain ID: ${CHAIN}\nNonce: ${id}\nExpires: ${expiresAt}\nRead and prepare fictional Ada's Pharmacy workflow. No transaction authorization.`;this.store.insert('challenge',id,{message,expiresAt,used:false});return {id,message,expiresAt,owner:this.owner,chainId:CHAIN};}
 async authenticate(id:string,signature:Hex,chainId:number){ensure(chainId===CHAIN,'WRONG_CHAIN');const c=this.store.get<Challenge>('challenge',id);ensure(c&&!c.used&&this.clock()<c.expiresAt,'INVALID_CHALLENGE');ensure(await verifyMessage({address:this.owner as Address,message:c.message,signature}),'WRONG_WALLET_OR_SIGNATURE');return this.store.atomic(()=>{const fresh=this.store.get<Challenge>('challenge',id)!;ensure(!fresh.used,'REPLAY');this.store.replace('challenge',id,{...fresh,used:true});const token=randomBytes(32).toString('hex');this.store.insert('session',hash(token),{owner:this.owner,expiresAt:this.clock()+3600000});return {token,expiresAt:this.clock()+3600000};});}
 session(token:string){const s=this.store.get<{owner:string;expiresAt:number}>('session',hash(token));ensure(s&&s.expiresAt>this.clock()&&s.owner===this.owner,'UNAUTHORIZED');return s;}
 account(){const now=this.clock();const g=this.graph();const counts={runs:this.store.list('run').length,offers:this.store.list('offer').length,receipts:this.store.list('receipt').length};const key='account:'+this.owner;const existing=this.store.get<AccountRow>('account',key);const base:AccountRow=existing??{address:this.owner,business:g.name,graphId:g.id,graphVersion:g.version,graphAsOf:g.asOf,createdAt:now,lastSeenAt:0,runs:0,offers:0,receipts:0};const row:AccountRow={...base,graphVersion:g.version,graphAsOf:g.asOf,lastSeenAt:now,...counts};if(!existing){this.store.insert('account',key,{...row,createdAt:now});this.store.audit({event:'ACCOUNT_CREATED',account:this.owner,at:now});}else{this.store.replace('account',key,row);this.store.audit({event:'ACCOUNT_SYNCED',account:this.owner,at:now});}return row;}
 run(intent:unknown){const q=validateAgentIntent(intent);const r=analyze(this.graph(),q,this.clock());if(!this.store.get('run',r.id)){this.store.insert('run',r.id,r);this.store.audit({event:'ANALYSIS_COMPLETED',runId:r.id,hash:r.runHash,at:this.clock()});}return r;}
 offer(runId:string){const r=this.store.get<Run>('run',runId);ensure(r,'RUN_NOT_FOUND');const salt=this.store.get<string>('private','commitment-salt')!;return this.store.atomic(()=>{ensure(!this.store.list<Offer>('offer').some(o=>o.status!=='REPAID'),'DUPLICATE_FINANCING');const o=issueOffer(this.graph(),r,this.owner,salt,this.clock());ensure(!this.store.list<Offer>('offer').some(x=>x.obligationCommitment===o.obligationCommitment),'DUPLICATE_FINANCING');this.store.insert('offer',o.id,o);this.store.audit({event:'OFFER_PROPOSED',offer:o.id,at:this.clock()});return o;});}
 getOffer(id:string){const o=this.store.get<Offer>('offer',id);ensure(o,'OFFER_NOT_FOUND');return o;}
 deployment(){return deployment(this.owner);}
 async registerDeployment(tx:Hex){const d=await verifyDeployment(tx,this.owner);this.store.atomic(()=>{ensure(!this.store.get('deployment','active'),'DEPLOYMENT_ALREADY_REGISTERED');this.store.insert('deployment','active',d);this.store.audit({event:'DEPLOYMENT_VERIFIED',...d});});return d;}
 approval(id:string){const o=this.getOffer(id);authorizeOffer(o,this.graph(),this.owner,this.clock(),CHAIN);const d=this.store.get<{address:string}>('deployment','active');ensure(d,'DEPLOYMENT_REQUIRED');return {message:approvalMessage(o,d.address),offer:o,contract:d.address};}
 async approve(id:string,signature:Hex,chainId:number){const {message,contract}=this.approval(id);ensure(chainId===CHAIN,'WRONG_CHAIN');ensure(await verifyMessage({address:this.owner as Address,message,signature}),'INVALID_SIGNATURE');return this.store.atomic(()=>{const o=this.getOffer(id);authorizeOffer(o,this.graph(),this.owner,this.clock(),chainId);ensure(o.status==='PROPOSED','APPROVAL_REPLAY');const updated={...o,status:'APPROVED' as const,contract};this.store.replace('offer',id,updated);this.store.insert('approval',id,{message,signature,actor:this.owner,at:this.clock()});this.store.audit({event:'HUMAN_APPROVED',offer:id,messageHash:hash(message),at:this.clock()});return updated;});}
 prepare(id:string,action:'allowance'|'register'|'draw'|'repay',amount?:string){const o=this.getOffer(id);ensure(['APPROVED','REGISTERED','DRAWN'].includes(o.status),'HUMAN_APPROVAL_REQUIRED');if(action!=='repay'&&o.status!=='DRAWN')authorizeOffer(o,this.graph(),this.owner,this.clock(),CHAIN);ensure(this.store.get('approval',id),'HUMAN_APPROVAL_REQUIRED');return transaction(o,action,amount);}
 async reconcile(id:string,tx:Hex){const before=this.getOffer(id);const receipt=await verifyReceipt(before,tx);return this.store.atomic(()=>{const o=this.getOffer(id);ensure(hash(o)===hash(before),'CONCURRENT_CHANGE');ensure(!this.store.get('receipt',receipt.id),'DUPLICATE_REPAYMENT');this.store.insert('receipt',receipt.id,receipt);if(receipt.event==='Registered')o.status='REGISTERED';if(receipt.event==='Drawn')o.status='DRAWN';if(receipt.event==='Repaid'){o.repaid=receipt.total;if(receipt.complete)o.status='REPAID';const g=this.graph();g.history.push({agreementId:id,receiptId:receipt.id,principalUSDC:o.principal,repaidUSDC:receipt.amount,amountNGN:Number(BigInt(receipt.amount)*BigInt(o.fx.nairaPerUSDC*100)/1000000n),onTime:receipt.timestamp<=o.dueAt,blockNumber:receipt.blockNumber,transactionHash:tx,chainId:CHAIN,mode:'REAL — TESTNET'});g.version++;this.store.replace('graph',g.id,g);}this.store.replace('offer',id,o);this.store.audit({event:'RECEIPT_RECONCILED',receiptId:receipt.id,offer:id,graphHash:hash(this.graph()),at:this.clock()});return {receipt,offer:o,graph:this.graph()};});}
}
